### ISSUE TITLE
Test Todo Model and Controller

### ISSUE THREAD

**Issue by mrman511** [mrman511/event-manager-ruby#12]
## Todo Controller
 - [x] create
     - [x] expect response status to be 200
     - [x] expect todo instance to have id
     - [x] expect keys to match values used to instantiate instance
     - [x] expect response to be a Hash
 - [x] read
     - [x] expect response status to be 200
     - [x] expect response to be Array
 - [x] read :id
      - [x] expect response status to be 200
      - [x] expect id of the instance to be the same as requested id
      - [x] expect response to be a Hash
 - [x] update
      - [x] expect response status to be 200
      - [x] expect response "message" to be "Todo updated"
      - [x] expect updated key of instance to match value updated to
 - [x] delete
      - [x] expect response status to be 200
      - [x] expect response "message" to be "Todo destroyed"

## Todo Model
- [x] is valid
